export const PRESET_SUBJECTS = [
  { name: 'Physics 1st Paper', color: '#534AB7', group: 'Science' },
  { name: 'Physics 2nd Paper', color: '#6B62CA', group: 'Science' },
  { name: 'Chemistry 1st Paper', color: '#1D9E75', group: 'Science' },
  { name: 'Chemistry 2nd Paper', color: '#2EB589', group: 'Science' },
  { name: 'Biology 1st Paper', color: '#D85A30', group: 'Science' },
  { name: 'Biology 2nd Paper', color: '#EF754D', group: 'Science' },
  { name: 'Higher Math 1st Paper', color: '#EF9F27', group: 'Science' },
  { name: 'Higher Math 2nd Paper', color: '#F6B147', group: 'Science' },
  { name: 'Economics', color: '#E14C85', group: 'Humanities' },
  { name: 'Civics & Governance', color: '#9E4482', group: 'Humanities' },
  { name: 'Logic', color: '#44849E', group: 'Humanities' },
  { name: 'Sociology', color: '#889E44', group: 'Humanities' },
  { name: 'Islamic History', color: '#9E7444', group: 'Humanities' },
  { name: 'Geography', color: '#559E44', group: 'Humanities' },
  { name: 'Accounting', color: '#3A70C2', group: 'Business' },
  { name: 'Finance & Banking', color: '#4B3AC2', group: 'Business' },
  { name: 'Business Organisation', color: '#8E3AC2', group: 'Business' },
  { name: 'Marketing', color: '#C23A8C', group: 'Business' },
  { name: 'Bangla 1st Paper', color: '#5F5E5A', group: 'Compulsory' },
  { name: 'Bangla 2nd Paper', color: '#73726E', group: 'Compulsory' },
  { name: 'English 1st Paper', color: '#272624', group: 'Compulsory' },
  { name: 'English 2nd Paper', color: '#3D3B39', group: 'Compulsory' },
  { name: 'ICT', color: '#1B566E', group: 'Compulsory' }
];
